export * from './types.js';
export { PROFILES, getProfile } from './profiles.js';
export { analyze, type AnalyzeOptions } from './analyze/index.js';
export { runRules, RULE_IDS } from './rules.js';
export { optimize, type OptimizeOptions, type OptimizeSummary, type TextureEncoder } from './optimize.js';
export { createNodeIO } from './io.js';
export { extrudeImage, extrudeFromRgba, type ExtrudeOptions, type ExtrudeResult, type LayerInfo } from './extrude/index.js';
export { detectKtx2Encoder, ktx2Compress, type Ktx2Encoder } from './ktx2.js';
export { stripMaterials } from './optimize.js';
export { toStl, type StlOptions, type StlResult } from './stl.js';
export { detectGenerator, type GeneratorGuess, type GeneratorProfile } from './detect.js';
export { alignmentScore, sampleSurface, triangleSoup, type AlignmentScore } from './harness/align.js';
export { renderViews, defaultRig, type RenderedView, type RenderCamera } from './harness/render.js';
