#!/usr/bin/env node
/**
 * Fold the pass files into docs/agent-loop/ledger.md.
 *
 * The ledger used to be one hand-edited file that every pass prepended to,
 * which made it the one place concurrent passes were guaranteed to collide:
 * three open PRs, three new sections at line 13, three conflicts. A finding
 * is also not a diary entry — its state changes over time, and a reader
 * wants "what is open right now", which a reverse-chronological log makes
 * you reconstruct by reading the whole thing.
 *
 * So passes/ is append-only — one new file per pass, and a new file never
 * conflicts — and this regenerates the index from it. Later passes override
 * earlier ones for the same finding id, so closing L2 is just writing
 * `### L2 · `fixed` · …` in your own file.
 *
 * The format is what the loop already wrote, so there is nothing extra to
 * remember:
 *
 *   # Pass — YYYY-MM-DD — <commit or run id>
 *   ### L<n> · `state` · <title>
 *
 * states: open | fixed | wontfix | watching
 *
 *   node scripts/ledger.mjs            # regenerate
 *   node scripts/ledger.mjs --check    # exit 1 if stale (CI)
 *
 * On a merge conflict in ledger.md, do not resolve it by hand: take either
 * side and re-run this.
 */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const dir = join(root, 'docs', 'agent-loop', 'passes');
const out = join(root, 'docs', 'agent-loop', 'ledger.md');

const STATES = new Set(['open', 'fixed', 'wontfix', 'watching']);
const HEAD = /^#\s+Pass\s+—\s+(\d{4}-\d{2}-\d{2})\s+—\s+(.+?)\s*$/m;
const FINDING = /^###\s+(L\d+)\s+·\s+`([a-z]+)`\s+·\s+(.+?)\s*$/gm;

const problems = [];

const files = (await readdir(dir)).filter((f) => f.endsWith('.md')).sort();
const passes = [];
for (const file of files) {
  const text = await readFile(join(dir, file), 'utf8');
  const head = text.match(HEAD);
  if (!head) { problems.push(`${file}: no "# Pass — YYYY-MM-DD — <ref>" heading`); continue; }
  const findings = [];
  for (const m of text.matchAll(FINDING)) {
    const [, id, state, title] = m;
    if (!STATES.has(state)) problems.push(`${file}: ${id} has state \`${state}\`; expected one of ${[...STATES].join(', ')}`);
    findings.push({ id, state, title });
  }
  const seen = new Set();
  for (const f of findings) {
    if (seen.has(f.id)) problems.push(`${file}: ${f.id} appears twice — one heading per finding per pass`);
    seen.add(f.id);
  }
  if (!findings.length) problems.push(`${file}: no findings. A pass that found nothing still records that as a finding, so the next pass knows the ground was walked`);
  passes.push({ file, date: head[1], ref: head[2], findings });
}

// Sort by date, then filename, so two passes on one day stay deterministic.
passes.sort((a, b) => (a.date === b.date ? a.file.localeCompare(b.file) : a.date.localeCompare(b.date)));

if (problems.length) {
  console.error('Pass files are malformed:\n' + problems.map((p) => `  - ${p}`).join('\n'));
  process.exit(2);
}

// Fold: the last pass to mention a finding owns its state.
const current = new Map();
for (const p of passes) {
  for (const f of p.findings) {
    const first = current.get(f.id)?.first ?? p;
    current.set(f.id, { ...f, first, last: p });
  }
}
const byId = [...current.values()].sort((a, b) => Number(a.id.slice(1)) - Number(b.id.slice(1)));
const openish = byId.filter((f) => f.state === 'open' || f.state === 'watching');
const closed = byId.filter((f) => f.state === 'fixed' || f.state === 'wontfix');

const link = (p) => `passes/${p.file}`;
const row = (f) => `| \`${f.id}\` | ${f.state} | ${f.title} | [${f.first.date}](${link(f.first)}) | [${f.last.date}](${link(f.last)}) |`;

const L = [];
L.push('<!-- Generated by scripts/ledger.mjs from docs/agent-loop/passes/. Do not edit:');
L.push('     write your finding in your own pass file and run `pnpm ledger`. -->');
L.push('');
L.push('# Agent-loop ledger');
L.push('');
L.push('Every finding the loop has made, and where it stands **now**. A pass reads');
L.push('this first, so that pass 40 does not spend its budget rediscovering what');
L.push('pass 3 wrote down, and does not re-file something closed as working as');
L.push('intended.');
L.push('');
L.push('One file per pass in [`passes/`](passes/), append-only. A later pass changes');
L.push('a finding\'s state by writing its own heading for that id — the newest');
L.push('mention wins, and this index is regenerated from all of them.');
L.push('');
L.push(`**${openish.length} open** · ${closed.length} closed · ${passes.length} passes`);
L.push('');
L.push('## Open');
L.push('');
if (openish.length) {
  L.push('| id | state | finding | first seen | last touched |');
  L.push('|---|---|---|---|---|');
  for (const f of openish) L.push(row(f));
} else {
  L.push('Nothing open.');
}
L.push('');
L.push('## Closed');
L.push('');
L.push('| id | state | finding | first seen | last touched |');
L.push('|---|---|---|---|---|');
for (const f of closed) L.push(row(f));
L.push('');
L.push('## Passes');
L.push('');
for (const p of [...passes].reverse()) {
  L.push(`- **${p.date}** — [${p.file.replace(/\.md$/, '')}](${link(p)}) — \`${p.ref}\` — ${p.findings.map((f) => `\`${f.id}\` ${f.state}`).join(', ')}`);
}
L.push('');

const text = L.join('\n');
if (process.argv.includes('--check')) {
  const existing = await readFile(out, 'utf8').catch(() => '');
  if (existing !== text) {
    console.error('docs/agent-loop/ledger.md is stale — run `pnpm ledger` and commit the result.');
    process.exit(1);
  }
  console.log(`ledger.md is in sync (${byId.length} findings across ${passes.length} passes).`);
} else {
  await writeFile(out, text);
  console.log(`ledger.md: ${openish.length} open, ${closed.length} closed, ${passes.length} passes.`);
}
